'use client';

import Link from 'next/link';
import '../../src/components/auth/Auth.css';
import '../../src/app.css';

export default function TermsPage() {
  return (
    <div className="gradient-background">
      <div className="auth-container" style={{ padding: '2rem', width: '100%', maxWidth: '1200px', margin: '0 auto' }}>
        <div className="auth-card" style={{ maxHeight: '90vh', overflowY: 'auto', width: '100%', maxWidth: '900px' }}>
          <div style={{ marginBottom: '2rem', textAlign: 'center', borderBottom: '1px solid rgba(255, 255, 255, 0.3)', paddingBottom: '1rem' }}>
            <div style={{ display: 'flex', justifyContent: 'center', gap: '1rem', marginBottom: '1rem', flexWrap: 'wrap' }}>
              <Link href="/login" style={{ color: '#ffffff', textDecoration: 'none', padding: '0.5rem 1rem', background: 'rgba(255, 255, 255, 0.2)', borderRadius: '5px', fontWeight: '600' }}>
                Login
              </Link>
              <Link href="/register" style={{ color: '#ffffff', textDecoration: 'none', padding: '0.5rem 1rem', background: 'rgba(255, 255, 255, 0.2)', borderRadius: '5px', fontWeight: '600' }}>
                Sign Up
              </Link>
            </div>
          </div>
          
          <div style={{ color: '#ffffff', lineHeight: '1.8' }}>
            <h1 style={{ marginBottom: '1rem', fontSize: '2.5rem' }}>TERMS OF USE</h1>
            <p style={{ marginBottom: '1.5rem', opacity: 0.9 }}><strong>Last updated: January 26, 2026</strong></p>
            
            <h2 style={{ marginTop: '2rem', marginBottom: '1rem', fontSize: '2rem' }}>AGREEMENT TO OUR LEGAL TERMS</h2>
            <p style={{ marginBottom: '1.5rem' }}>We are Thoughts ("Company," "we," "us," "our"), a company registered in Pakistan at Multan, Punjab 66000.</p>
            <p style={{ marginBottom: '1.5rem' }}>We operate the website <a href="thoughts.nauman.live" target="_blank" rel="noopener noreferrer" style={{ color: '#ffffff', textDecoration: 'underline' }}>thoughts.nauman.live</a> (the "Site"), the mobile application Thoughts (the "App"), as well as any other related products and services that refer or link to these legal terms (the "Legal Terms") (collectively, the "Services").</p>
            <p style={{ marginBottom: '1.5rem' }}>Thoughts is a minimalist web app that helps you capture, organize, and manage your daily thoughts and to-dos in one simple, distraction-free place.</p>
            <p style={{ marginBottom: '1.5rem' }}>You can contact us by phone at +923146601881, email at <a href="mailto:inaumanmajeed@gmail.com" style={{ color: '#ffffff', textDecoration: 'underline' }}>inaumanmajeed@gmail.com</a>, or by mail to Multan, Punjab 66000, Pakistan.</p>
            <p style={{ marginBottom: '1.5rem' }}>These Legal Terms constitute a legally binding agreement made between you, whether personally or on behalf of an entity ("you"), and Thoughts, concerning your access to and use of the Services. You agree that by accessing the Services, you have read, understood, and agreed to be bound by all of these Legal Terms. IF YOU DO NOT AGREE WITH ALL OF THESE LEGAL TERMS, THEN YOU ARE EXPRESSLY PROHIBITED FROM USING THE SERVICES AND YOU MUST DISCONTINUE USE IMMEDIATELY.</p>
            <p style={{ marginBottom: '1.5rem' }}>We will provide you with prior notice of any scheduled changes to the Services you are using. The modified Legal Terms will become effective upon posting or notifying you by <a href="mailto:inaumanmajeed@gmail.com" style={{ color: '#ffffff', textDecoration: 'underline' }}>inaumanmajeed@gmail.com</a>, as stated in the email message. By continuing to use the Services after the effective date of any changes, you agree to be bound by the modified terms.</p>
            <p style={{ marginBottom: '1.5rem' }}>All users who are minors in the jurisdiction in which they reside (generally under the age of 18) must have the permission of, and be directly supervised by, their parent or guardian to use the Services. If you are a minor, you must have your parent or guardian read and agree to these Legal Terms prior to you using the Services.</p>
            <p style={{ marginBottom: '1.5rem' }}>We recommend that you print a copy of these Legal Terms for your records.</p>
            
            <h2 style={{ marginTop: '2rem', marginBottom: '1rem', fontSize: '2rem' }}>TABLE OF CONTENTS</h2>
            <ul style={{ marginBottom: '1.5rem', paddingLeft: '1.5rem' }}>
              <li style={{ marginBottom: '0.5rem' }}><a href="#services" style={{ color: '#ffffff', textDecoration: 'underline' }}>1. OUR SERVICES</a></li>
              <li style={{ marginBottom: '0.5rem' }}><a href="#ip" style={{ color: '#ffffff', textDecoration: 'underline' }}>2. INTELLECTUAL PROPERTY RIGHTS</a></li>
              <li style={{ marginBottom: '0.5rem' }}><a href="#userreps" style={{ color: '#ffffff', textDecoration: 'underline' }}>3. USER REPRESENTATIONS</a></li>
              <li style={{ marginBottom: '0.5rem' }}><a href="#userreg" style={{ color: '#ffffff', textDecoration: 'underline' }}>4. USER REGISTRATION</a></li>
              <li style={{ marginBottom: '0.5rem' }}><a href="#prohibited" style={{ color: '#ffffff', textDecoration: 'underline' }}>5. PROHIBITED ACTIVITIES</a></li>
              <li style={{ marginBottom: '0.5rem' }}><a href="#ugc" style={{ color: '#ffffff', textDecoration: 'underline' }}>6. USER GENERATED CONTRIBUTIONS</a></li>
              <li style={{ marginBottom: '0.5rem' }}><a href="#license" style={{ color: '#ffffff', textDecoration: 'underline' }}>7. CONTRIBUTION LICENSE</a></li>
              <li style={{ marginBottom: '0.5rem' }}><a href="#mobile" style={{ color: '#ffffff', textDecoration: 'underline' }}>8. MOBILE APPLICATION LICENSE</a></li>
              <li style={{ marginBottom: '0.5rem' }}><a href="#sitemanage" style={{ color: '#ffffff', textDecoration: 'underline' }}>9. SERVICES MANAGEMENT</a></li>
              <li style={{ marginBottom: '0.5rem' }}><a href="#ppyes" style={{ color: '#ffffff', textDecoration: 'underline' }}>10. PRIVACY POLICY</a></li>
              <li style={{ marginBottom: '0.5rem' }}><a href="#terms" style={{ color: '#ffffff', textDecoration: 'underline' }}>11. TERM AND TERMINATION</a></li>
              <li style={{ marginBottom: '0.5rem' }}><a href="#modifications" style={{ color: '#ffffff', textDecoration: 'underline' }}>12. MODIFICATIONS AND INTERRUPTIONS</a></li>
              <li style={{ marginBottom: '0.5rem' }}><a href="#law" style={{ color: '#ffffff', textDecoration: 'underline' }}>13. GOVERNING LAW</a></li>
              <li style={{ marginBottom: '0.5rem' }}><a href="#disputes" style={{ color: '#ffffff', textDecoration: 'underline' }}>14. DISPUTE RESOLUTION</a></li>
              <li style={{ marginBottom: '0.5rem' }}><a href="#corrections" style={{ color: '#ffffff', textDecoration: 'underline' }}>15. CORRECTIONS</a></li>
              <li style={{ marginBottom: '0.5rem' }}><a href="#disclaimer" style={{ color: '#ffffff', textDecoration: 'underline' }}>16. DISCLAIMER</a></li>
              <li style={{ marginBottom: '0.5rem' }}><a href="#liability" style={{ color: '#ffffff', textDecoration: 'underline' }}>17. LIMITATIONS OF LIABILITY</a></li>
              <li style={{ marginBottom: '0.5rem' }}><a href="#indemnification" style={{ color: '#ffffff', textDecoration: 'underline' }}>18. INDEMNIFICATION</a></li>
              <li style={{ marginBottom: '0.5rem' }}><a href="#userdata" style={{ color: '#ffffff', textDecoration: 'underline' }}>19. USER DATA</a></li>
              <li style={{ marginBottom: '0.5rem' }}><a href="#electronic" style={{ color: '#ffffff', textDecoration: 'underline' }}>20. ELECTRONIC COMMUNICATIONS, TRANSACTIONS, AND SIGNATURES</a></li>
              <li style={{ marginBottom: '0.5rem' }}><a href="#california" style={{ color: '#ffffff', textDecoration: 'underline' }}>21. CALIFORNIA USERS AND RESIDENTS</a></li>
              <li style={{ marginBottom: '0.5rem' }}><a href="#misc" style={{ color: '#ffffff', textDecoration: 'underline' }}>22. MISCELLANEOUS</a></li>
              <li style={{ marginBottom: '0.5rem' }}><a href="#contact" style={{ color: '#ffffff', textDecoration: 'underline' }}>23. CONTACT US</a></li>
            </ul>
            
            <h2 id="services" style={{ marginTop: '2rem', marginBottom: '1rem', fontSize: '2rem' }}>1. OUR SERVICES</h2>
            <p style={{ marginBottom: '1.5rem' }}>The information provided when using the Services is not intended for distribution to or use by any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation or which would subject us to any registration requirement within such jurisdiction or country. Accordingly, those persons who choose to access the Services from other locations do so on their own initiative and are solely responsible for compliance with local laws, if and to the extent local laws are applicable.</p>
            <p style={{ marginBottom: '1.5rem' }}>The Services are not tailored to comply with industry-specific regulations (Health Insurance Portability and Accountability Act (HIPAA), Federal Information Security Management Act (FISMA), etc.), so if your interactions would be subjected to such laws, you may not use the Services. You may not use the Services in a way that would violate the Gramm-Leach-Bliley Act (GLBA).</p>
            
            <h2 id="ip" style={{ marginTop: '2rem', marginBottom: '1rem', fontSize: '2rem' }}>2. INTELLECTUAL PROPERTY RIGHTS</h2>
            <h3 style={{ marginTop: '1.5rem', marginBottom: '0.75rem', fontSize: '1.5rem' }}>Our intellectual property</h3>
            <p style={{ marginBottom: '1rem' }}>We are the owner or the licensee of all intellectual property rights in our Services, including all source code, databases, functionality, software, website designs, audio, video, text, photographs, and graphics in the Services (collectively, the "Content"), as well as the trademarks, service marks, and logos contained therein (the "Marks").</p>
            <p style={{ marginBottom: '1rem' }}>Our Content and Marks are protected by copyright and trademark laws (and various other intellectual property rights and unfair competition laws) and treaties in the United States and around the world.</p>
            <p style={{ marginBottom: '1rem' }}>The Content and Marks are provided in or through the Services "AS IS" for your personal, non-commercial use or internal business purpose only.</p>
            
            <h3 style={{ marginTop: '1.5rem', marginBottom: '0.75rem', fontSize: '1.5rem' }}>Your use of our Services</h3>
            <p style={{ marginBottom: '1rem' }}>Subject to your compliance with these Legal Terms, including the <a href="#prohibited" style={{ color: '#ffffff', textDecoration: 'underline' }}>PROHIBITED ACTIVITIES</a> section below, we grant you a non-exclusive, non-transferable, revocable license to:</p>
            <ul style={{ marginBottom: '1rem', paddingLeft: '1.5rem' }}>
              <li style={{ marginBottom: '0.5rem' }}>access the Services; and</li>
              <li style={{ marginBottom: '0.5rem' }}>download or print a copy of any portion of the Content to which you have properly gained access,</li>
            </ul>
            <p style={{ marginBottom: '1rem' }}>solely for your personal, non-commercial use or internal business purpose.</p>
            <p style={{ marginBottom: '1rem' }}>Except as set out in this section or elsewhere in our Legal Terms, no part of the Services and no Content or Marks may be copied, reproduced, aggregated, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted, distributed, sold, licensed, or otherwise exploited for any commercial purpose whatsoever, without our express prior written permission.</p>
            <p style={{ marginBottom: '1rem' }}>If you wish to make any use of the Services, Content, or Marks other than as set out in this section or elsewhere in our Legal Terms, please address your request to: <a href="mailto:inaumanmajeed@gmail.com" style={{ color: '#ffffff', textDecoration: 'underline' }}>inaumanmajeed@gmail.com</a>. If we ever grant you the permission to post, reproduce, or publicly display any part of our Services or Content, you must identify us as the owners or licensors of the Services, Content, or Marks and ensure that any copyright or proprietary notice appears or is visible on posting, reproducing, or displaying our Content.</p>
            <p style={{ marginBottom: '1rem' }}>We reserve all rights not expressly granted to you in and to the Services, Content, and Marks.</p>
            <p style={{ marginBottom: '1rem' }}>Any breach of these Intellectual Property Rights will constitute a material breach of our Legal Terms and your right to use our Services will terminate immediately.</p>
            
            <h3 style={{ marginTop: '1.5rem', marginBottom: '0.75rem', fontSize: '1.5rem' }}>Your submissions</h3>
            <p style={{ marginBottom: '1rem' }}>Please review this section and the <a href="#prohibited" style={{ color: '#ffffff', textDecoration: 'underline' }}>PROHIBITED ACTIVITIES</a> section carefully prior to using our Services to understand the (a) rights you give us and (b) obligations you have when you post or upload any content through the Services.</p>
            <p style={{ marginBottom: '1rem' }}><strong>Submissions:</strong> By directly sending us any question, comment, suggestion, idea, feedback, or other information about the Services ("Submissions"), you agree to assign to us all intellectual property rights in such Submission. You agree that we shall own this Submission and be entitled to its unrestricted use and dissemination for any lawful purpose, commercial or otherwise, without acknowledgment or compensation to you.</p>
            <p style={{ marginBottom: '1rem' }}><strong>You are responsible for what you post or upload:</strong> By sending us Submissions through any part of the Services you:</p>
            <ul style={{ marginBottom: '1rem', paddingLeft: '1.5rem' }}>
              <li style={{ marginBottom: '0.75rem' }}>confirm that you have read and agree with our <a href="#prohibited" style={{ color: '#ffffff', textDecoration: 'underline' }}>PROHIBITED ACTIVITIES</a> and will not post, send, publish, upload, or transmit through the Services any Submission that is illegal, harassing, hateful, harmful, defamatory, obscene, bullying, abusive, discriminatory, threatening to any person or group, sexually explicit, false, inaccurate, deceitful, or misleading;</li>
              <li style={{ marginBottom: '0.75rem' }}>to the extent permissible by applicable law, waive any and all moral rights to any such Submission;</li>
              <li style={{ marginBottom: '0.75rem' }}>warrant that any such Submission are original to you or that you have the necessary rights and licenses to submit such Submissions and that you have full authority to grant us the above-mentioned rights in relation to your Submissions; and</li>
              <li style={{ marginBottom: '0.75rem' }}>warrant and represent that your Submissions do not constitute confidential information.</li>
            </ul>
            <p style={{ marginBottom: '1.5rem' }}>You are solely responsible for your Submissions and you expressly agree to reimburse us for any and all losses that we may suffer because of your breach of (a) this section, (b) any third party's intellectual property rights, or (c) applicable law.</p>
            
            <h2 id="userreps" style={{ marginTop: '2rem', marginBottom: '1rem', fontSize: '2rem' }}>3. USER REPRESENTATIONS</h2>
            <p style={{ marginBottom: '1rem' }}>By using the Services, you represent and warrant that: (1) all registration information you submit will be true, accurate, current, and complete; (2) you will maintain the accuracy of such information and promptly update such registration information as necessary; (3) you have the legal capacity and you agree to comply with these Legal Terms; (4) you are not a minor in the jurisdiction in which you reside, or if a minor, you have received parental permission to use the Services; (5) you will not access the Services through automated or non-human means, whether through a bot, script or otherwise; (6) you will not use the Services for any illegal or unauthorized purpose; and (7) your use of the Services will not violate any applicable law or regulation.</p>
            <p style={{ marginBottom: '1.5rem' }}>If you provide any information that is untrue, inaccurate, not current, or incomplete, we have the right to suspend or terminate your account and refuse any and all current or future use of the Services (or any portion thereof).</p>
            
            <h2 id="userreg" style={{ marginTop: '2rem', marginBottom: '1rem', fontSize: '2rem' }}>4. USER REGISTRATION</h2>
            <p style={{ marginBottom: '1.5rem' }}>You may be required to register to use the Services. You agree to keep your password confidential and will be responsible for all use of your account and password. We reserve the right to remove, reclaim, or change a username you select if we determine, in our sole discretion, that such username is inappropriate, obscene, or otherwise objectionable.</p>
            
            <h2 id="prohibited" style={{ marginTop: '2rem', marginBottom: '1rem', fontSize: '2rem' }}>5. PROHIBITED ACTIVITIES</h2>
            <p style={{ marginBottom: '1rem' }}>You may not access or use the Services for any purpose other than that for which we make the Services available. The Services may not be used in connection with any commercial endeavors except those that are specifically endorsed or approved by us.</p>
            <p style={{ marginBottom: '1rem' }}>As a user of the Services, you agree not to:</p>
            <ul style={{ marginBottom: '1.5rem', paddingLeft: '1.5rem' }}>
              <li style={{ marginBottom: '0.75rem' }}>Systematically retrieve data or other content from the Services to create or compile, directly or indirectly, a collection, compilation, database, or directory without written permission from us.</li>
              <li style={{ marginBottom: '0.75rem' }}>Trick, defraud, or mislead us and other users, especially in any attempt to learn sensitive account information such as user passwords.</li>
              <li style={{ marginBottom: '0.75rem' }}>Circumvent, disable, or otherwise interfere with security-related features of the Services, including features that prevent or restrict the use or copying of any Content or enforce limitations on the use of the Services and/or the Content contained therein.</li>
              <li style={{ marginBottom: '0.75rem' }}>Disparage, tarnish, or otherwise harm, in our opinion, us and/or the Services.</li>
              <li style={{ marginBottom: '0.75rem' }}>Use any information obtained from the Services in order to harass, abuse, or harm another person.</li>
              <li style={{ marginBottom: '0.75rem' }}>Make improper use of our support services or submit false reports of abuse or misconduct.</li>
              <li style={{ marginBottom: '0.75rem' }}>Use the Services in a manner inconsistent with any applicable laws or regulations.</li>
              <li style={{ marginBottom: '0.75rem' }}>Engage in unauthorized framing of or linking to the Services.</li>
              <li style={{ marginBottom: '0.75rem' }}>Upload or transmit (or attempt to upload or to transmit) viruses, Trojan horses, or other material, including excessive use of capital letters and spamming (continuous posting of repetitive text), that interferes with any party's uninterrupted use and enjoyment of the Services or modifies, impairs, disrupts, alters, or interferes with the use, features, functions, operation, or maintenance of the Services.</li>
              <li style={{ marginBottom: '0.75rem' }}>Engage in any automated use of the system, such as using scripts to send comments or messages, or using any data mining, robots, or similar data gathering and extraction tools.</li>
              <li style={{ marginBottom: '0.75rem' }}>Delete the copyright or other proprietary rights notice from any Content.</li>
              <li style={{ marginBottom: '0.75rem' }}>Attempt to impersonate another user or person or use the username of another user.</li>
              <li style={{ marginBottom: '0.75rem' }}>Upload or transmit (or attempt to upload or to transmit) any material that acts as a passive or active information collection or transmission mechanism, including without limitation, clear graphics interchange formats ("gifs"), 1×1 pixels, web bugs, cookies, or other similar devices (sometimes referred to as "spyware" or "passive collection mechanisms" or "pcms").</li>
              <li style={{ marginBottom: '0.75rem' }}>Interfere with, disrupt, or create an undue burden on the Services or the networks or services connected to the Services.</li>
              <li style={{ marginBottom: '0.75rem' }}>Harass, annoy, intimidate, or threaten any of our employees or agents engaged in providing any portion of the Services to you.</li>
              <li style={{ marginBottom: '0.75rem' }}>Attempt to bypass any measures of the Services designed to prevent or restrict access to the Services, or any portion of the Services.</li>
              <li style={{ marginBottom: '0.75rem' }}>Copy or adapt the Services' software, including but not limited to Flash, PHP, HTML, JavaScript, or other code.</li>
              <li style={{ marginBottom: '0.75rem' }}>Except as permitted by applicable law, decipher, decompile, disassemble, or reverse engineer any of the software comprising or in any way making up a part of the Services.</li>
              <li style={{ marginBottom: '0.75rem' }}>Except as may be the result of standard search engine or Internet browser usage, use, launch, develop, or distribute any automated system, including without limitation, any spider, robot, cheat utility, scraper, or offline reader that accesses the Services, or use or launch any unauthorized script or other software.</li>
              <li style={{ marginBottom: '0.75rem' }}>Use a buying agent or purchasing agent to make purchases on the Services.</li>
              <li style={{ marginBottom: '0.75rem' }}>Make any unauthorized use of the Services, including collecting usernames and/or email addresses of users by electronic or other means for the purpose of sending unsolicited email, or creating user accounts by automated means or under false pretenses.</li>
              <li style={{ marginBottom: '0.75rem' }}>Use the Services as part of any effort to compete with us or otherwise use the Services and/or the Content for any revenue-generating endeavor or commercial enterprise.</li>
              <li style={{ marginBottom: '0.75rem' }}>Use the Services to advertise or offer to sell goods and services.</li>
              <li style={{ marginBottom: '0.75rem' }}>Sell or otherwise transfer your profile.</li>
              <li style={{ marginBottom: '0.75rem' }}>Unlawful words</li>
            </ul>
            
            <h2 id="ugc" style={{ marginTop: '2rem', marginBottom: '1rem', fontSize: '2rem' }}>6. USER GENERATED CONTRIBUTIONS</h2>
            <p style={{ marginBottom: '1rem' }}>The Services does not offer users to submit or post content. We may provide you with the opportunity to create, submit, post, display, transmit, perform, publish, distribute, or broadcast content and materials to us or on the Services, including but not limited to text, writings, video, audio, photographs, graphics, comments, suggestions, or personal information or other material (collectively, "Contributions"). Contributions may be viewable by other users of the Services and through third-party websites. As such, any Contributions you transmit may be treated in accordance with the Services' Privacy Policy. When you create or make available any Contributions, you thereby represent and warrant that:</p>
            <ul style={{ marginBottom: '1.5rem', paddingLeft: '1.5rem' }}>
              <li style={{ marginBottom: '0.75rem' }}>The creation, distribution, transmission, public display, or performance, and the accessing, downloading, or copying of your Contributions do not and will not infringe the proprietary rights, including but not limited to the copyright, patent, trademark, trade secret, or moral rights of any third party.</li>
              <li style={{ marginBottom: '0.75rem' }}>You are the creator and owner of or have the necessary licenses, rights, consents, releases, and permissions to use and to authorize us, the Services, and other users of the Services to use your Contributions in any manner contemplated by the Services and these Legal Terms.</li>
              <li style={{ marginBottom: '0.75rem' }}>You have the written consent, release, and/or permission of each and every identifiable individual person in your Contributions to use the name or likeness of each and every such identifiable individual person to enable inclusion and use of your Contributions in any manner contemplated by the Services and these Legal Terms.</li>
              <li style={{ marginBottom: '0.75rem' }}>Your Contributions are not false, inaccurate, or misleading.</li>
              <li style={{ marginBottom: '0.75rem' }}>Your Contributions are not unsolicited or unauthorized advertising, promotional materials, pyramid schemes, chain letters, spam, mass mailings, or other forms of solicitation.</li>
              <li style={{ marginBottom: '0.75rem' }}>Your Contributions are not obscene, lewd, lascivious, filthy, violent, harassing, libelous, slanderous, or otherwise objectionable (as determined by us).</li>
              <li style={{ marginBottom: '0.75rem' }}>Your Contributions do not ridicule, mock, disparage, intimidate, or abuse anyone.</li>
              <li style={{ marginBottom: '0.75rem' }}>Your Contributions are not used to harass or threaten (in the legal sense of those terms) any other person and to promote violence against a specific person or class of people.</li>
              <li style={{ marginBottom: '0.75rem' }}>Your Contributions do not violate any applicable law, regulation, or rule.</li>
              <li style={{ marginBottom: '0.75rem' }}>Your Contributions do not violate the privacy or publicity rights of any third party.</li>
              <li style={{ marginBottom: '0.75rem' }}>Your Contributions do not violate any applicable law concerning child pornography, or otherwise intended to protect the health or well-being of minors.</li>
              <li style={{ marginBottom: '0.75rem' }}>Your Contributions do not include any offensive comments that are connected to race, national origin, gender, sexual preference, or physical handicap.</li>
              <li style={{ marginBottom: '0.75rem' }}>Your Contributions do not otherwise violate, or link to material that violates, any provision of these Legal Terms, or any applicable law or regulation.</li>
            </ul>
            <p style={{ marginBottom: '1.5rem' }}>Any use of the Services in violation of the foregoing violates these Legal Terms and may result in, among other things, termination or suspension of your rights to use the Services.</p>
            
            <h2 id="license" style={{ marginTop: '2rem', marginBottom: '1rem', fontSize: '2rem' }}>7. CONTRIBUTION LICENSE</h2>
            <p style={{ marginBottom: '1rem' }}>You and Services agree that we may access, store, process, and use any information and personal data that you provide following the terms of the Privacy Policy and your choices (including settings).</p>
            <p style={{ marginBottom: '1rem' }}>By submitting suggestions or other feedback regarding the Services, you agree that we can use and share such feedback for any purpose without compensation to you.</p>
            <p style={{ marginBottom: '1.5rem' }}>We do not assert any ownership over your Contributions. You retain full ownership of all of your Contributions and any intellectual property rights or other proprietary rights associated with your Contributions. We are not liable for any statements or representations in your Contributions provided by you in any area on the Services. You are solely responsible for your Contributions to the Services and you expressly agree to exonerate us from any and all responsibility and to refrain from any legal action against us regarding your Contributions.</p>
            
            <h2 id="mobile" style={{ marginTop: '2rem', marginBottom: '1rem', fontSize: '2rem' }}>8. MOBILE APPLICATION LICENSE</h2>
            <h3 style={{ marginTop: '1.5rem', marginBottom: '0.75rem', fontSize: '1.5rem' }}>Use License</h3>
            <p style={{ marginBottom: '1rem' }}>If you access the Services via the App, then we grant you a revocable, non-exclusive, non-transferable, limited right to install and use the App on wireless electronic devices owned or controlled by you, and to access and use the App on such devices strictly in accordance with the terms and conditions of this mobile application license contained in these Legal Terms. You shall not: (1) except as permitted by applicable law, decompile, reverse engineer, disassemble, attempt to derive the source code of, or decrypt the App; (2) make any modification, adaptation, improvement, enhancement, translation, or derivative work from the App; (3) violate any applicable laws, rules, or regulations in connection with your access or use of the App; (4) remove, alter, or obscure any proprietary notice (including any notice of copyright or trademark) posted by us or the licensors of the App; (5) use the App for any revenue-generating endeavor, commercial enterprise, or other purpose for which it is not designed or intended; (6) make the App available over a network or other environment permitting access or use by multiple devices or users at the same time; (7) use the App for creating a product, service, or software that is, directly or indirectly, competitive with or in any way a substitute for the App; (8) use the App to send automated queries to any website or to send any unsolicited commercial email; or (9) use any proprietary information or any of our interfaces or our other intellectual property in the design, development, manufacture, licensing, or distribution of any applications, accessories, or devices for use with the App.</p>
            
            <h3 style={{ marginTop: '1.5rem', marginBottom: '0.75rem', fontSize: '1.5rem' }}>Apple and Android Devices</h3>
            <p style={{ marginBottom: '1.5rem' }}>The following terms apply when you use the App obtained from either the Apple Store or Google Play (each an "App Distributor") to access the Services: (1) the license granted to you for our App is limited to a non-transferable license to use the application on a device that utilizes the Apple iOS or Android operating systems, as applicable, and in accordance with the usage rules set forth in the applicable App Distributor's terms of service; (2) we are responsible for providing any maintenance and support services with respect to the App as specified in the terms and conditions of this mobile application license contained in these Legal Terms or as otherwise required under applicable law, and you acknowledge that each App Distributor has no obligation whatsoever to furnish any maintenance and support services with respect to the App; (3) in the event of any failure of the App to conform to any applicable warranty, you may notify the applicable App Distributor, and the App Distributor, in accordance with its terms and policies, may refund the purchase price, if any, paid for the App, and to the maximum extent permitted by applicable law, the App Distributor will have no other warranty obligation whatsoever with respect to the App; (4) you represent and warrant that (i) you are not located in a country that is subject to a US government embargo, or that has been designated by the US government as a "terrorist supporting" country and (ii) you are not listed on any US government list of prohibited or restricted parties; (5) you must comply with applicable third-party terms of agreement when using the App, e.g., if you have a VoIP application, then you must not be in violation of their wireless data service agreement when using the App; and (6) you acknowledge and agree that the App Distributors are third-party beneficiaries of the terms and conditions in this mobile application license contained in these Legal Terms, and that each App Distributor will have the right (and will be deemed to have accepted the right) to enforce the terms and conditions in this mobile application license contained in these Legal Terms against you as a third-party beneficiary thereof.</p>
            
            <h2 id="sitemanage" style={{ marginTop: '2rem', marginBottom: '1rem', fontSize: '2rem' }}>9. SERVICES MANAGEMENT</h2>
            <p style={{ marginBottom: '1.5rem' }}>We reserve the right, but not the obligation, to: (1) monitor the Services for violations of these Legal Terms; (2) take appropriate legal action against anyone who, in our sole discretion, violates the law or these Legal Terms, including without limitation, reporting such user to law enforcement authorities; (3) in our sole discretion and without limitation, refuse, restrict access to, limit the availability of, or disable (to the extent technologically feasible) any of your Contributions or any portion thereof; (4) in our sole discretion and without limitation, notice, or liability, to remove from the Services or otherwise disable all files and content that are excessive in size or are in any way burdensome to our systems; and (5) otherwise manage the Services in a manner designed to protect our rights and property and to facilitate the proper functioning of the Services.</p>
            
            <h2 id="ppyes" style={{ marginTop: '2rem', marginBottom: '1rem', fontSize: '2rem' }}>10. PRIVACY POLICY</h2>
            <p style={{ marginBottom: '1.5rem' }}>We care about data privacy and security. Please review our Privacy Policy: <strong><a href="/privacy" style={{ color: '#ffffff', textDecoration: 'underline' }}>thoughts.nauman.live/privacy</a></strong>. By using the Services, you agree to be bound by our Privacy Policy, which is incorporated into these Legal Terms. Please be advised the Services are hosted in Pakistan. If you access the Services from any other region of the world with laws or other requirements governing personal data collection, use, or disclosure that differ from applicable laws in Pakistan, then through your continued use of the Services, you are transferring your data to Pakistan, and you expressly consent to have your data transferred to and processed in Pakistan.</p>
            
            <h2 id="terms" style={{ marginTop: '2rem', marginBottom: '1rem', fontSize: '2rem' }}>11. TERM AND TERMINATION</h2>
            <p style={{ marginBottom: '1rem' }}>These Legal Terms shall remain in full force and effect while you use the Services. WITHOUT LIMITING ANY OTHER PROVISION OF THESE LEGAL TERMS, WE RESERVE THE RIGHT TO, IN OUR SOLE DISCRETION AND WITHOUT NOTICE OR LIABILITY, DENY ACCESS TO AND USE OF THE SERVICES (INCLUDING BLOCKING CERTAIN IP ADDRESSES), TO ANY PERSON FOR ANY REASON OR FOR NO REASON, INCLUDING WITHOUT LIMITATION FOR BREACH OF ANY REPRESENTATION, WARRANTY, OR COVENANT CONTAINED IN THESE LEGAL TERMS OR OF ANY APPLICABLE LAW OR REGULATION. WE MAY TERMINATE YOUR USE OR PARTICIPATION IN THE SERVICES OR DELETE YOUR ACCOUNT AND ANY CONTENT OR INFORMATION THAT YOU POSTED AT ANY TIME, WITHOUT WARNING, IN OUR SOLE DISCRETION.</p>
            <p style={{ marginBottom: '1.5rem' }}>If we terminate or suspend your account for any reason, you are prohibited from registering and creating a new account under your name, a fake or borrowed name, or the name of any third party, even if you may be acting on behalf of the third party. In addition to terminating or suspending your account, we reserve the right to take appropriate legal action, including without limitation pursuing civil, criminal, and injunctive redress.</p>
            
            <h2 id="modifications" style={{ marginTop: '2rem', marginBottom: '1rem', fontSize: '2rem' }}>12. MODIFICATIONS AND INTERRUPTIONS</h2>
            <p style={{ marginBottom: '1rem' }}>We reserve the right to change, modify, or remove the contents of the Services at any time or for any reason at our sole discretion without notice. However, we have no obligation to update any information on our Services. We will not be liable to you or any third party for any modification, price change, suspension, or discontinuance of the Services.</p>
            <p style={{ marginBottom: '1.5rem' }}>We cannot guarantee the Services will be available at all times. We may experience hardware, software, or other problems or need to perform maintenance related to the Services, resulting in interruptions, delays, or errors. We reserve the right to change, revise, update, suspend, discontinue, or otherwise modify the Services at any time or for any reason without notice to you. You agree that we have no liability whatsoever for any loss, damage, or inconvenience caused by your inability to access or use the Services during any downtime or discontinuance of the Services. Nothing in these Legal Terms will be construed to obligate us to maintain and support the Services or to supply any corrections, updates, or releases in connection therewith.</p>
            
            <h2 id="law" style={{ marginTop: '2rem', marginBottom: '1rem', fontSize: '2rem' }}>13. GOVERNING LAW</h2>
            <p style={{ marginBottom: '1.5rem' }}>These Legal Terms shall be governed by and defined following the laws of Pakistan. Thoughts and yourself irrevocably consent that the courts of Pakistan shall have exclusive jurisdiction to resolve any dispute which may arise in connection with these Legal Terms.</p>
            
            <h2 id="disputes" style={{ marginTop: '2rem', marginBottom: '1rem', fontSize: '2rem' }}>14. DISPUTE RESOLUTION</h2>
            <p style={{ marginBottom: '1.5rem' }}>You agree to irrevocably submit all disputes related to these Legal Terms or the legal relationship established by these Legal Terms to the jurisdiction of the Pakistan courts. Thoughts shall also maintain the right to bring proceedings as to the substance of the matter in the courts of the country where you reside or, if these Legal Terms are entered into in the course of your trade or profession, the state of your principal place of business.</p>
            
            <h2 id="corrections" style={{ marginTop: '2rem', marginBottom: '1rem', fontSize: '2rem' }}>15. CORRECTIONS</h2>
            <p style={{ marginBottom: '1.5rem' }}>There may be information on the Services that contains typographical errors, inaccuracies, or omissions, including descriptions, pricing, availability, and various other information. We reserve the right to correct any errors, inaccuracies, or omissions and to change or update the information on the Services at any time, without prior notice.</p>
            
            <h2 id="disclaimer" style={{ marginTop: '2rem', marginBottom: '1rem', fontSize: '2rem' }}>16. DISCLAIMER</h2>
            <p style={{ marginBottom: '1.5rem' }}>THE SERVICES ARE PROVIDED ON AN AS-IS AND AS-AVAILABLE BASIS. YOU AGREE THAT YOUR USE OF THE SERVICES WILL BE AT YOUR SOLE RISK. TO THE FULLEST EXTENT PERMITTED BY LAW, WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, IN CONNECTION WITH THE SERVICES AND YOUR USE THEREOF, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE MAKE NO WARRANTIES OR REPRESENTATIONS ABOUT THE ACCURACY OR COMPLETENESS OF THE SERVICES' CONTENT OR THE CONTENT OF ANY WEBSITES OR MOBILE APPLICATIONS LINKED TO THE SERVICES AND WE WILL ASSUME NO LIABILITY OR RESPONSIBILITY FOR ANY (1) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT AND MATERIALS, (2) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF THE SERVICES, (3) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (4) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE SERVICES, (5) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH THE SERVICES BY ANY THIRD PARTY, AND/OR (6) ANY ERRORS OR OMISSIONS IN ANY CONTENT AND MATERIALS OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE SERVICES. WE DO NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A THIRD PARTY THROUGH THE SERVICES, ANY HYPERLINKED WEBSITE, OR ANY WEBSITE OR MOBILE APPLICATION FEATURED IN ANY BANNER OR OTHER ADVERTISING, AND WE WILL NOT BE A PARTY TO OR IN ANY WAY BE RESPONSIBLE FOR MONITORING ANY TRANSACTION BETWEEN YOU AND ANY THIRD-PARTY PROVIDERS OF PRODUCTS OR SERVICES. AS WITH THE PURCHASE OF A PRODUCT OR SERVICE THROUGH ANY MEDIUM OR IN ANY ENVIRONMENT, YOU SHOULD USE YOUR BEST JUDGMENT AND EXERCISE CAUTION WHERE APPROPRIATE.</p>
            
            <h2 id="liability" style={{ marginTop: '2rem', marginBottom: '1rem', fontSize: '2rem' }}>17. LIMITATIONS OF LIABILITY</h2>
            <p style={{ marginBottom: '1.5rem' }}>IN NO EVENT WILL WE OR OUR DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY DIRECT, INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL, OR PUNITIVE DAMAGES, INCLUDING LOST PROFIT, LOST REVENUE, LOSS OF DATA, OR OTHER DAMAGES ARISING FROM YOUR USE OF THE SERVICES, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, OUR LIABILITY TO YOU FOR ANY CAUSE WHATSOEVER AND REGARDLESS OF THE FORM OF THE ACTION, WILL AT ALL TIMES BE LIMITED TO THE AMOUNT PAID, IF ANY, BY YOU TO US DURING THE ONE (1) MONTH PERIOD PRIOR TO ANY CAUSE OF ACTION ARISING. CERTAIN US STATE LAWS AND INTERNATIONAL LAWS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES OR THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE ABOVE DISCLAIMERS OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MAY HAVE ADDITIONAL RIGHTS.</p>
            
            <h2 id="indemnification" style={{ marginTop: '2rem', marginBottom: '1rem', fontSize: '2rem' }}>18. INDEMNIFICATION</h2>
            <p style={{ marginBottom: '1.5rem' }}>You agree to defend, indemnify, and hold us harmless, including our subsidiaries, affiliates, and all of our respective officers, agents, partners, and employees, from and against any loss, damage, liability, claim, or demand, including reasonable attorneys' fees and expenses, made by any third party due to or arising out of: (1) use of the Services; (2) breach of these Legal Terms; (3) any breach of your representations and warranties set forth in these Legal Terms; (4) your violation of the rights of a third party, including but not limited to intellectual property rights; or (5) any overt harmful act toward any other user of the Services with whom you connected via the Services. Notwithstanding the foregoing, we reserve the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us, and you agree to cooperate, at your expense, with our defense of such claims. We will use reasonable efforts to notify you of any such claim, action, or proceeding which is subject to this indemnification upon becoming aware of it.</p>
            
            <h2 id="userdata" style={{ marginTop: '2rem', marginBottom: '1rem', fontSize: '2rem' }}>19. USER DATA</h2>
            <p style={{ marginBottom: '1.5rem' }}>We will maintain certain data that you transmit to the Services for the purpose of managing the performance of the Services, as well as data relating to your use of the Services. Although we perform regular routine backups of data, you are solely responsible for all data that you transmit or that relates to any activity you have undertaken using the Services. You agree that we shall have no liability to you for any loss or corruption of any such data, and you hereby waive any right of action against us arising from any such loss or corruption of such data.</p>
            
            <h2 id="electronic" style={{ marginTop: '2rem', marginBottom: '1rem', fontSize: '2rem' }}>20. ELECTRONIC COMMUNICATIONS, TRANSACTIONS, AND SIGNATURES</h2>
            <p style={{ marginBottom: '1.5rem' }}>Visiting the Services, sending us emails, and completing online forms constitute electronic communications. You consent to receive electronic communications, and you agree that all agreements, notices, disclosures, and other communications we provide to you electronically, via email and on the Services, satisfy any legal requirement that such communication be in writing. YOU HEREBY AGREE TO THE USE OF ELECTRONIC SIGNATURES, CONTRACTS, ORDERS, AND OTHER RECORDS, AND TO ELECTRONIC DELIVERY OF NOTICES, POLICIES, AND RECORDS OF TRANSACTIONS INITIATED OR COMPLETED BY US OR VIA THE SERVICES. You hereby waive any rights or requirements under any statutes, regulations, rules, ordinances, or other laws in any jurisdiction which require an original signature or delivery or retention of non-electronic records, or to payments or the granting of credits by any means other than electronic means.</p>
            
            <h2 id="california" style={{ marginTop: '2rem', marginBottom: '1rem', fontSize: '2rem' }}>21. CALIFORNIA USERS AND RESIDENTS</h2>
            <p style={{ marginBottom: '1.5rem' }}>If any complaint with us is not satisfactorily resolved, you can contact the Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs in writing at 1625 North Market Blvd., Suite N 112, Sacramento, California 95834 or by telephone at (800) 952-5210 or (916) 445-1254.</p>
            
            <h2 id="misc" style={{ marginTop: '2rem', marginBottom: '1rem', fontSize: '2rem' }}>22. MISCELLANEOUS</h2>
            <p style={{ marginBottom: '1.5rem' }}>These Legal Terms and any policies or operating rules posted by us on the Services or in respect to the Services constitute the entire agreement and understanding between you and us. Our failure to exercise or enforce any right or provision of these Legal Terms shall not operate as a waiver of such right or provision. These Legal Terms operate to the fullest extent permissible by law. We may assign any or all of our rights and obligations to others at any time. We shall not be responsible or liable for any loss, damage, delay, or failure to act caused by any cause beyond our reasonable control. If any provision or part of a provision of these Legal Terms is determined to be unlawful, void, or unenforceable, that provision or part of the provision is deemed severable from these Legal Terms and does not affect the validity and enforceability of any remaining provisions. There is no joint venture, partnership, employment or agency relationship created between you and us as a result of these Legal Terms or use of the Services. You agree that these Legal Terms will not be construed against us by virtue of having drafted them. You hereby waive any and all defenses you may have based on the electronic form of these Legal Terms and the lack of signing by the parties hereto to execute these Legal Terms.</p>
            
            <h2 id="contact" style={{ marginTop: '2rem', marginBottom: '1rem', fontSize: '2rem' }}>23. CONTACT US</h2>
            <p style={{ marginBottom: '1rem' }}>In order to resolve a complaint regarding the Services or to receive further information regarding use of the Services, please contact us at:</p>
            <ul style={{ marginBottom: '2rem', paddingLeft: '1.5rem' }}>
              <li style={{ marginBottom: '0.5rem' }}><strong>Multan, Punjab 66000, Pakistan</strong></li>
              <li style={{ marginBottom: '0.5rem' }}><strong>Phone: +923146601881</strong></li>
              <li style={{ marginBottom: '0.5rem' }}><strong>Email: <a href="mailto:inaumanmajeed@gmail.com" style={{ color: '#ffffff', textDecoration: 'underline' }}>inaumanmajeed@gmail.com</a></strong></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}
